custom:
  clash_rule_base: https://raw.githubusercontent.com/MuXia-0326/rule/master/clash-rule/forcerule.yml

  proxy_groups:
    - { name: Proxies, type: select, rule: [ '[]HK`[]JP`[]SG`[]TW`[]US`[]ALL' ] }
    - { name: Bilibili, type: select, rule: [ '[]DIRECT`[]HK`[]TW' ] }
    - { name: Netflix, type: select, rule: [ '[]Proxies`[]HK`[]JP`[]SG`[]TW`[]US' ] }
    - { name: Bahamut, type: select, rule: [ '[]Proxies`[]TW' ] }
    - { name: Youtube, type: select, rule: [ '[]Proxies`[]DIRECT`[]HK`[]JP`[]SG`[]TW`[]US' ] }
    - { name: Discord, type: select, rule: [ '[]Proxies`[]DIRECT`[]HK`[]JP`[]SG`[]TW`[]US' ] }
    - { name: Microsoft, type: select, rule: [ '[]Proxies`[]DIRECT`[]HK`[]JP`[]SG`[]TW`[]US' ] }
    - { name: OpenAI, type: select, rule: [ '[]JP`[]SG`[]US' ] }
    - { name: GamePlatform, type: select, rule: [ '[]Proxies`[]DIRECT`[]HK`[]JP`[]SG`[]TW`[]US' ] }
    - { name: Nintendo, type: select, rule: [ '[]Proxies`[]DIRECT`[]HK`[]JP`[]SG`[]TW`[]US' ] }
    - { name: Final, type: select, rule: [ '[]Proxies`[]DIRECT' ] }
    - { name: HK, type: select, rule: [ '港|HK|Hong Kong`http://www.gstatic.com/generate_204`600' ] }
    - { name: JP, type: select, rule: [ '日((?!用).)+|东京|大阪|埼玉|JP|Japan`http://www.gstatic.com/generate_204`600' ] }
    - { name: SG, type: select, rule: [ '新|新加坡|狮城|SG|Singapore`http://www.gstatic.com/generate_204`600' ] }
    - { name: TW, type: select, rule: [ '台|新北|彰化|TW|Taiwan`http://www.gstatic.com/generate_204`600' ] }
    - { name: US, type: select, rule: [ '美|洛杉矶|硅谷|达拉斯|费利蒙|凤凰城|芝加哥|圣何塞|西雅图|US|America|USA`http://www.gstatic.com/generate_204`600' ] }
    - { name: CN, type: select, rule: [ '回国|网易|云音乐|Netease`http://www.gstatic.com/generate_204`600' ] }
    - { name: DST, type: select, rule: [ "鸭子乐园`http://www.gstatic.com/generate_204`600" ] }
    - { name: ALL, type: select, rule: [ '.*' ] }

  rulesets:
    # 自用
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/MuXia-0326/rule/master/my-rule/DIRECT.yaml', group: 'DIRECT' }
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/MuXia-0326/rule/master/my-rule/REJECT.yaml', group: 'REJECT' }
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/MuXia-0326/rule/master/my-rule/PROXY.yaml', group: 'Proxies' }
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/MuXia-0326/rule/master/my-rule/group/switch.yaml', group: 'Nintendo' }
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/MuXia-0326/rule/master/my-rule/group/openAI.yaml', group: 'OpenAI' }
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/MuXia-0326/rule/master/my-rule/group/DST.yaml', group: 'DST' }

    # 开源项目
    ## 广告
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite.yaml', group: 'REJECT' }
    ## 流媒体服务
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml', group: 'Netflix' }
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml', group: 'Bahamut' }
    ## 哔哩哔哩 分流
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml', group: 'Bilibili' }
    ## youtube 分流
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml', group: 'Youtube' }
    ## discord 分流
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord.yaml', group: 'Discord' }
    ## Microsoft 分流
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml', group: 'Microsoft' }
    ## Global.list - 国际网络分流
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.yaml', group: 'Proxies' }
    ## 游戏下载分流
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.yaml', group: 'GamePlatform' }
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml', group: 'GamePlatform' }
    # Nintendo代理规则
    - { ruleset: 'clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.yaml', group: 'Nintendo' }
    # CN
    - { ruleset: 'clash-classic:https://github.com/AkinoYuiko/X/blob/main/Clash/Rules/cncidr.yaml', group: 'DIRECT' }
    - { ruleset: '[]GEOIP,CN', group: 'DIRECT' }
    # NO_RULES
    - { ruleset: '[]MATCH', group: 'Proxies' }
